CREATE TABLE Items(Id CHAR(36) NOT NULL, Title NVARCHAR(256) NULL, Tags NVARCHAR(256) NULL, Body NTEXT NULL, CONSTRAINT PK_Items PRIMARY KEY(Id))

-- CREATE TABLE Tags(Id CHAR(36) NOT NULL, Name NVARCHAR(256) NOT NULL, CONSTRAINT PK_Tags PRIMARY KEY(Id), CONSTRAINT UQ_Name UNIQUE(Name))
-- CREATE TABLE Items_Tags(ItemId CHAR(32) NOT NULL, TagId CHAR(32) NOT NULL, CONSTRAINT PK_Items_Tags PRIMARY KEY(ItemId, TagId), CONSTRAINT FK_ItemId FOREIGN KEY(ItemId) REFERENCES Items(Id), CONSTRAINT FK_TagId FOREIGN KEY(TagId) REFERENCES Tags(Id))
